version: 2.1
jobs:
  build-publish-image:
    machine:
      enabled: true
    working_directory: ~/project
    steps:
    - checkout
    - run:
        name: "Build doker image"
        command: docker build --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --build-arg BUILD_VERSION=1.0.0 -t abazovic/fs-vanilla:0.0.2 -t abazovic/fs-vanilla:latest .
    - deploy:
        command: |
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              docker push abazovic/fs-vanilla
workflows:
  version: 2
  workflow:
    jobs:
    - build-publish-image